
<script language="JavaScript">
<!--
function jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
//-->
</script>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tr> 
    <td width="15%" background="http://www.inmetro.gov.br/global/img/cabap_03.gif"><a href="http://www.inmetro.gov.br"><img src="http://www.inmetro.gov.br/global/img/cabap_01.gif" width="52" height="55" border="0" alt="Volta &agrave; P&aacute;gina inicial do site do Inmetro"></a><img src="http://www.inmetro.gov.br/global/img/cabap_02.gif" width="60" height="55" border="0"></td>
      <td background="http://www.inmetro.gov.br/global/img/cabap_03.gif" width="64%" align="right" valign="middle"> 
        <div style="font-family: Arial, Helvetica, sans-serif; font-size: 8pt"> 
          <select name="conteudo" style="font-family: Arial, Helvetica, sans-serif; font-size: 8pt" onChange="jumpMenu('top',this,1)">
            <option value="#" style="background:#e5e5e5" selected>- - - - - - - - Site do Inmetro - - - - - - - -</option>
            <option value="http://www.inmetro.gov.br/inmetro" style="background:#e5e5e5">Conhe&ccedil;a o Inmetro</option>
            <option value="http://www.inmetro.gov.br/metLegal" style="background:#f5f5f5">Metrologia Legal</option>
            <option value="http://www.inmetro.gov.br/metcientifica" style="background:#e5e5e5">Metrologia 
            Cient&iacute;fica e Industrial</option>
            <option value="http://www.inmetro.gov.br/qualidade" style="background:#f5f5f5">Qualidade</option>
            <option value="http://www.inmetro.gov.br/consumidor" style="background:#e5e5e5">Informa&ccedil;&otilde;es 
            ao Consumidor</option>
            <option value="http://www.inmetro.gov.br/fiscalizacao" style="background:#f5f5f5">Fiscaliza&ccedil;&atilde;o</option>
            <option value="http://www.inmetro.gov.br/infotec" style="background:#e5e5e5">Informa&ccedil;&atilde;o 
            Tecnol&oacute;gica</option>
            <option value="http://www.inmetro.gov.br/servicos" style="background:#f5f5f5">Servi&ccedil;os</option>
            <option value="http://www.inmetro.gov.br/laboratorios" style="background:#e5e5e5">Laborat&oacute;rios</option>
            <option value="http://www.inmetro.gov.br/organismos" style="background:#f5f5f5">Organismos Credenciados</option>
            <option value="http://www.inmetro.gov.br/articulacoes" style="background:#e5e5e5">Barreiras Técnicas 
            às Exportações</option>
            <option value="http://www.inmetro.gov.br/legislacao" style="background:#f5f5f5">Legisla&ccedil;&atilde;o</option>
            <option value="http://www.inmetro.gov.br/inmetro/planejamento.asp" style="background:#e5e5e5">Planejamento 
            Estrat&eacute;gico</option>
            <option value="http://www.inmetro.gov.br/inmetro/contrato.asp" style="background:#f5f5f5">Contrato 
            de Gest&atilde;o</option>
            <option value="http://www.inmetro.gov.br/noticias" style="background:#e5e5e5">Not&iacute;cias 
            e Eventos</option>
          </select>
        </div>
    </td>
    <td align="right" width="21%" background="http://www.inmetro.gov.br/global/img/cabap_03.gif"><img src="http://www.inmetro.gov.br/global/img/cabap_04.gif" width="49" height="55" border="0"><a href="http://www.inmetro.gov.br/ouvidoria/falecom.asp"><img src="http://www.inmetro.gov.br/global/img/cabap_05.gif" width="44" height="55" border="0" alt="Fale com o Inmetro"></a><a href="http://www.inmetro.gov.br/ouvidoria/ouvidoria.asp"><img src="http://www.inmetro.gov.br/global/img/cabap_06.gif" width="40" height="55" border="0" alt="Ouvidoria"></a><a href="http://www.inmetro.gov.br/busca/mapa.asp"><img src="http://www.inmetro.gov.br/global/img/cabap_07.gif" width="42" height="55" border="0" alt="Mapa do site"></a><a href="http://www.inmetro.gov.br/busca/sites.asp"><img src="http://www.inmetro.gov.br/global/img/cabap_08.gif" width="44" height="55" border="0" alt="Sites de interesse"></a><img src="http://www.inmetro.gov.br/global/img/cabap_09.gif" width="34" height="55" border="0"></td>
  </tr>
</table>

